#!/usr/bin/env node
/**
 * Pre-render script for SSG
 *
 * Usage:
 *   # First build client and server:
 *   pnpm build:client
 *   pnpm build:server
 *
 *   # Then pre-render:
 *   node dist/server/prerender.js --data ./data.json --output ./dist/client
 */
import { existsSync, mkdirSync, readFileSync, writeFileSync, copyFileSync, rmSync } from 'node:fs'
import { join, resolve } from 'node:path'

interface Options {
  data: string
  output: string
  basePath: string
}

function parseArgs(): Options {
  const args = process.argv.slice(2)
  const options: Options = { data: '', output: '', basePath: '/' }

  for (let i = 0; i < args.length; i++) {
    if (args[i] === '--data' || args[i] === '-d') options.data = args[++i]
    else if (args[i] === '--output' || args[i] === '-o') options.output = args[++i]
    else if (args[i] === '--base-path' || args[i] === '-b') options.basePath = args[++i]
  }

  if (!options.data || !options.output) {
    console.error('Usage: node prerender.js --data <data.json> --output <dir>')
    process.exit(1)
  }

  return options
}

async function prerender() {
  const { data, output, basePath } = parseArgs()
  const outputDir = resolve(output)
  const dataPath = resolve(data)

  console.log('\n=== OpenSpec UI Pre-render ===\n')

  // 1. Read data.json
  const snapshot = JSON.parse(readFileSync(dataPath, 'utf-8'))
  console.log(`Data: ${snapshot.specs.length} specs, ${snapshot.changes.length} changes`)

  // 2. Read HTML template (generated by vite build)
  const templatePath = join(outputDir, 'index.html')
  if (!existsSync(templatePath)) {
    throw new Error(`Template not found: ${templatePath}\nRun 'pnpm build:client' first.`)
  }
  const template = readFileSync(templatePath, 'utf-8')

  // 3. Import SSR module
  const { render, getRoutes, getTitle } = await import('./entry-server.js')

  // 4. Pre-render each route
  const routes = getRoutes(snapshot)
  console.log(`Routes: ${routes.length}\n`)

  // Generate head tags for injecting data
  const headTags = `
    <script>
      window.__OPENSPEC_BASE_PATH__ = '${basePath}';
      window.__OPENSPEC_STATIC_MODE__ = true;
      window.__INITIAL_DATA__ = ${JSON.stringify(snapshot)};
    </script>`

  for (const route of routes) {
    const appHtml = await render(route, snapshot, basePath)
    const title = getTitle(route, snapshot)

    const html = template
      .replace('<!--app-html-->', appHtml)
      .replace('<!--head-tags-->', headTags)
      .replace('<title>OpenSpec UI</title>', `<title>${title} - OpenSpec UI</title>`)

    // Write HTML file
    if (route === '/') {
      writeFileSync(join(outputDir, 'index.html'), html)
    } else {
      const routeDir = join(outputDir, route.slice(1))
      mkdirSync(routeDir, { recursive: true })
      writeFileSync(join(routeDir, 'index.html'), html)
    }
    console.log(`  ${route}`)
  }

  // 5. Copy index.html to 404.html
  copyFileSync(join(outputDir, 'index.html'), join(outputDir, '404.html'))

  // 6. Copy data.json to output
  copyFileSync(dataPath, join(outputDir, 'data.json'))

  // 7. Cleanup .vite directory
  const viteDir = join(outputDir, '.vite')
  if (existsSync(viteDir)) {
    rmSync(viteDir, { recursive: true })
  }

  console.log(`\nDone! ${routes.length} pages generated.\n`)
}

prerender().catch(err => {
  console.error('Pre-render failed:', err.message)
  process.exit(1)
})
